AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true
  Include:
    - app/**/*
    - lib/**/*
  Exclude:
    - app/views/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/tasks/**/*
    - spec/**/*
    - test/**/*

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - app/api/**/*

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile
    - Capfile
    - Rakefile

Style/Lambda:
  EnforcedStyle: literal

Style/Documentation:
  Enabled: false
